sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t houssemmaalej/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true houssemmaalej/docker-react npm run test

